import { StyleSheet } from 'react-native';
import { w, h, font } from './dimensions';

export const styles = StyleSheet.create({

  container: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    textAlign: 'center',
    width: w(100),
  },

  diningLocationContainer: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    width: w(100),
  },

  selectedDiningLocationContainer: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flexDirection: 'row',
    justifyContent: 'center',
    width: w(100),
  },

  foodItemContainer: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    width: w(100),
  },

  selectedFoodItemContainer: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flexDirection: 'row',
    justifyContent: 'center',
    width: w(100),
  },

  savedFoodItemMessageContainer: {
    alignItems: 'center',
    backgroundColor: '#AB0006',
    width: w(100),
  },

  scrollView: {
    alignSelf: 'stretch',
    flex: 1,
  },

  scrollContent: {
    alignItems: 'center',
    paddingBottom: h(6.0),
    width: w(100),
  },

  statusbar: {
    alignItems: 'center',
    backgroundColor: '#AB0006',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: h(2.0),
    paddingBottom: h(2.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    width: w(100),
  },

  headerTitle: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(250),
    fontWeight: '800',
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    paddingTop: h(0.5),
    paddingBottom: h(0.5),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(60),
  },

  headerUsernameIcon: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '700',
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    width: w(40),
  },

  headerButtonDefault: {
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#131312',
    borderColor: '#666666',    
    borderRadius: 20,
    borderWidth: 2,    
    justifyContent: 'center',
    maxHeight: h(10),    
    minWidth: w(25),
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
  },

  headerButtonTextDefault: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '700',
    textAlign: 'center',
  },

  savedFoodItemText: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    flexDirection: 'row',
    fontFamily: 'arial',
    fontSize: font(250),
    fontWeight: '700',
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(100),
  },

  infoText: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    color: '#FFFFFF',
    flexDirection: 'row',
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '600',
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(100),
  },

  diningLocationNameTextInput: {
    alignItems: 'center',
    backgroundColor: "#FFFFFF",
    color: '#131312',
    borderColor: '#131312',
    borderRadius: 15,
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    marginTop: h(2.0),
    marginBottom: h(2.0),
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    width: w(80),
  },

  diningLocationTextDefault: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    color: '#131312',
    borderColor: '#131312',
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '600',
    justifyContent: 'center',
    marginTop: h(2.0),
    marginBottom: h(2.0),
    paddingTop: h(5.0),
    paddingBottom: h(5.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    textAlign: 'center',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(100),
  },

  foodItemTextDefault: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    color: '#131312',
    borderColor: '#131312',
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '600',
    justifyContent: 'center',
    marginTop: h(2.0),
    marginBottom: h(2.0),
    paddingTop: h(5.0),
    paddingBottom: h(5.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    textAlign: 'center',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(100),
  },

  foodItemLabelText: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    color: '#131312',
    borderWidth: 1,
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '500',
    justifyContent: 'center',
    marginTop: h(2.0),
    marginBottom: h(2.0),
    paddingTop: h(5.0),
    paddingBottom: h(5.0),
    paddingLeft: w(4.0),
    paddingRight: w(2.0),
    textAlign: 'left',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(35),
  },

  foodItemDataText: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    color: '#131312',
    borderWidth: 1,
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '500',
    justifyContent: 'center',
    marginTop: h(2.0),
    marginBottom: h(2.0),
    paddingTop: h(5.0),
    paddingBottom: h(5.0),
    paddingLeft: w(4.0),
    paddingRight: w(2.0),
    textAlign: 'left',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(65),
  },

  bodyButtonDefault: {
    alignItems: 'center',
    backgroundColor: '#131312',
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#666666',
    height: h(15),
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    marginLeft: w(0.5),
    marginRight: w(0.5),
    paddingTop: h(2.0),
    paddingBottom: h(2.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    width: w(80),
  },

  bodyButtonTextDefault: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: 'bold',
    textAlign: 'center',
  },

  bodyButtonAlt: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#666666',
    height: h(15),
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    marginLeft: w(0.5),
    marginRight: w(0.5),
    paddingTop: h(2.0),
    paddingBottom: h(2.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    width: w(80),
  },

  bodyButtonTextAlt: {
    backgroundColor: 'transparent',
    color: '#C5151A',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: 'bold',
    textAlign: 'center',
  },



  

  foodInfoText: {
    backgroundColor: '#FFFFFF',
    borderWidth: 5,
    borderTopColor: '#666666',
    borderBottomColor: '#666666',
    color: '#131312',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: '600',
    marginTop: h(1.5),
    marginBottom: h(1.5),
    paddingTop: h(5),
    paddingBottom: h(5),
    paddingLeft: w(5),
    paddingRight: w(5),
    textAlign: 'center',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(100),
  },

  diningInfoText: {
    backgroundColor: '#FFFFFF',
    borderWidth: 5,
    borderTopColor: '#666666',
    borderBottomColor: '#666666',
    color: '#131312',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: '600',
    marginTop: h(1.5),
    marginBottom: h(1.5),
    paddingTop: h(5),
    paddingBottom: h(5),
    paddingLeft: w(5),
    paddingRight: w(5),
    textAlign: 'center',
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(100),
  },

  diningLocationNameTextInput: {
    backgroundColor: "#FFFFFF",
    color: '#131312',
    borderColor: '#131312',
    borderRadius: 15,
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    marginBottom: h(5),
    paddingTop: h(1.5),
    paddingBottom: h(1.5),
    paddingLeft: w(1.5),
    paddingRight: w(1.5),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    width: w(80),
  },

});
