import { StyleSheet } from "react-native";
import { w, h, font } from './dimensions';

export const styles = StyleSheet.create({

  container: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    overflow: 'scroll',
    textAlign: 'center',
    width: w(100),
  },

  headerContainer: {
    width: w(10),
  },

  bodyContainer: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: w(80),
  },

  statusbar: {
    alignItems: 'center',
    backgroundColor: '#AB0006',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: h(2.0),
    paddingBottom: h(2.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    width: w(100),
  },

  headerButton: {
    alignItems: 'center',
    backgroundColor: '#131312',
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#666666',
    color: 'red',
    height: h(10),
    justifyContent: 'center',
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    width: w(25),
  },

  headerButtonText: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '600',
    justifyContent: 'center',
  },

  headerTitle: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(250),
    fontWeight: '800',
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    paddingTop: h(0.5),
    paddingBottom: h(0.5),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(60),
  },

  headerUsernameIcon: {
    backgroundColor: '#AB0006',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '600',
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(40),
  },

  infoText: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    color: '#FFFFFF',
    flexDirection: 'row',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '600',
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    paddingTop: h(1.0),
    paddingBottom: h(1.0),
    paddingLeft: w(1.0),
    paddingRight: w(1.0),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(80),
  },

  bodyButton: {
    alignItems: 'center',
    backgroundColor: '#131312',
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#666666',
    height: h(15),
    justifyContent: 'center',
    marginTop: h(1.0),
    marginBottom: h(1.0),
    marginLeft: w(0.5),
    marginRight: w(0.5),
    paddingTop: h(2.0),
    paddingBottom: h(2.0),
    paddingLeft: w(2.0),
    paddingRight: w(2.0),
    width: w(60),
  },

  bodyButtonText: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: '600',
    textAlign: 'center',
  }

});