import { StyleSheet } from 'react-native';
import { w, h, font } from './dimensions';

export const styles = StyleSheet.create({

  container: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    textAlign: 'center',
    width: w(100),
  },

  scrollContent: {
    alignItems: 'center',
    paddingBottom: h(6),
    width: w(100),
  },

  scrollView: {
    alignSelf: 'stretch',
    flex: 1,
  },

  headerContainer: {
    backgroundColor: '#C5151A',
    width: w(10),
  },

  statusbar: {
    alignItems: 'center',
    backgroundColor: '#C5151A',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: h(1),
    paddingHorizontal: w(2),
    textAlign: 'center',
    width: w(100),
  },

  headerButton: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#131312',
    borderRadius: 50,
    borderWidth: 2,
    borderColor: 'white',
    paddingVertical: h(1.2),
    paddingHorizontal: w(3),
    minWidth: w(18),
    maxHeight: h(6),
  },

  headerButtonText: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '600',
    textAlign: 'center',
  },

  bodyButton: {
    alignItems: 'center',
    backgroundColor: '#131312',
    borderRadius: 50,
    borderWidth: 4,
    borderColor: '#131312',
    marginBottom: h(2.5),
    padding: h(2.5),
    width: w(40),
  },

  bodyButtonText: {
    backgroundColor: '#131312',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: '600',
    textAlign: 'center',
  },

  bodyButtonAlt: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    marginBottom: h(2.5),
    padding: h(2.5),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 10,
    width: w(40),
  },

  bodyButtonTextAlt: {
    backgroundColor: '#FFFFFF',
    color: '#C5151A',
    fontFamily: 'arial',
    fontSize: font(175),
    fontWeight: '600',
    textAlign: 'center',
  },

  headerTitle: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(280),
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    flex: 1,
  },

  headerUsernameIcon: {
    backgroundColor: 'transparent',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(110),
    fontWeight: 'bold',
    textAlign: 'center',
    marginRight: w(1),
    maxWidth: w(15),
  },

  infoText: {
    backgroundColor: '#C5151A',
    color: '#FFFFFF',
    fontFamily: 'arial',
    fontSize: font(150),
    fontWeight: '500',
    marginTop: h(0.5),
    paddingTop: h(5),
    paddingBottom: h(5),
    textAlign: 'center',
    textShadowColor: '#131312',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
    width: w(100),
  },

  usernameReqTitle: {
    backgroundColor: '#FFFFFF',
    color: '#666666',
    fontFamily: 'arial',
    fontSize: font(120),
    fontWeight: '600',
    marginTop: h(0.5),
    paddingTop: h(1.5),
    paddingBottom: h(1.5),
    textAlign: 'center',
    width: w(100),
  },

  usernameReqInfoText: {
    backgroundColor: '#FFFFFF',
    color: '#666666',
    fontFamily: 'arial',
    fontSize: font(100),
    fontWeight: '500',
    paddingBottom: h(1),
    textAlign: 'center',
    width: w(100),
  },

  passwordReqTitle: {
    backgroundColor: '#FFFFFF',
    color: '#666666',
    fontFamily: 'arial',
    fontSize: font(120),
    fontWeight: '600',
    paddingTop: h(1.5),
    paddingBottom: h(1.5),
    textAlign: 'center',
    width: w(100),
  },

  passwordReqInfoText: {
    backgroundColor: '#FFFFFF',
    color: '#666666',
    fontFamily: 'arial',
    fontSize: font(100),
    fontWeight: '500',
    paddingBottom: h(1),
    textAlign: 'center',
    width: w(100),
  },

  errorInfoText: {
    backgroundColor: "#FFFFFF",
    color: '#131312',
    fontFamily: 'arial',
    fontSize: font(125),
    fontWeight: '500',
    marginTop: h(1.5),
    paddingTop: h(5),
    paddingBottom: h(5),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    textAlign: 'center',
    width: w(100),
  },

  usernameTextInput: {
    backgroundColor: "#FFFFFF",
    color: '#131312',
    borderColor: '#131312',
    borderRadius: 15,
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    marginTop: h(5),
    marginBottom: h(2.5),
    paddingTop: h(1.5),
    paddingBottom: h(1.5),
    paddingLeft: w(1.5),
    paddingRight: w(1.5),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    width: w(75),
  },

  passwordTextInput: {
    backgroundColor: "#FFFFFF",
    color: '#131312',
    borderColor: '#131312',
    borderRadius: 15,
    borderWidth: 2,
    fontFamily: 'arial',
    fontSize: font(150),
    marginBottom: h(5),
    paddingTop: h(1.5),
    paddingBottom: h(1.5),
    paddingLeft: w(1.5),
    paddingRight: w(1.5),
    shadowColor: '#131312',
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 2,
    width: w(75),
  },

});
