import { SetStateAction, useState, useContext } from 'react';
import { View, Text, TextInput, TouchableOpacity } from 'react-native';

import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';

import { styles } from './styles/style-register';

import { useUser } from './context';

export default function RegisterScreen() {

    const { setUser } = useUser();
    const [error, setError] = useState('');

    ////////////////////////////////////////////////// Set the error elements //////////////////////////////////////////////////

    // Create constants for elements that will be modified based on the error generated by registration attempts
    const errorMessage = document.getElementById("errorMessage") as HTMLElement;

    /*
    Reset the attributes of error-related elements
    */
    function resetErrorElements() {
        if (errorMessage != null) {
            errorMessage.textContent = '';
            errorMessage.style.fontWeight = '800';
        }
    }

    ////////////////////////////////////////////////// Set the error elements //////////////////////////////////////////////////

    ////////////////////////////////////////////////// Testing username and password submissions //////////////////////////////////////////////////
    /* 
    Check if a string variable contains any lowercase letters
    str: The string variable to be tested
    returns: true if the string variable contains any lowercase letters
    */
    function containsLowerCaseLetters(str: string) {
        const lowerCaseLetters = /[abcdefghijklmnopqrstuvwxyz]/;
        return lowerCaseLetters.test(str);
    }

    /*
    Check if a string variable contains any uppercase letters
    str: The string variable to be tested
    returns: true if the string variable contains any uppercase letters
    */
    function containsUpperCaseLetters(str: string) {
        const upperCaseLetters = /[ABCDEFGHIJKLMNOPQRSTUVWXYZ]/;
        return upperCaseLetters.test(str);
    }

    /*
    Check if a string variable contains any numbers
    str: The string variable to be created
    returns: true if the string variable contains any numbers
    */
    function containsNumbers(str: string) {
        const numbers = /[1234567890]/;
        return numbers.test(str);
    }

    /*
    Check if a string variable contains any special characters
    str: The string variable to be created
    returns: true if the string variable contains any special characters
    */
    function containsSpecialChars(str: string) {
        const specialChars = /[`!@#$%^&*()+\-=\[\]{};':"\\|,.<>\/?~ ]/;
        return specialChars.test(str);
    }
    ////////////////////////////////////////////////// Testing username and password submissions //////////////////////////////////////////////////

    ////////////////////////////////////////////////// Username, Password, and Loading Variables and Setters //////////////////////////////////////////////////
    const [loading, setLoading] = useState('');

    // The username and password variables
    // These values are passed to a JSON object that is sent to the register endpoint
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    /*
    Set the value of the username variable to the value entered in the username text input element
    event: The event is the current string value in the username text input element
    */
    function saveUsernameInputText(event: { target: { value: SetStateAction<string>; }; }) {
        resetErrorElements();
        setUsername(event.target.value);
    }

    /*
    Set the value of the password variable to the value entered in the password text input element
    event: The event is the current string value in the password text input element
    */
    function savePasswordInputText(event: { target: { value: SetStateAction<string>; }; }) {
        resetErrorElements();
        setPassword(event.target.value);
    }
    ////////////////////////////////////////////////// Username, Password, and Loading Variables and Setters //////////////////////////////////////////////////

    ////////////////////////////////////////////////// Send register request //////////////////////////////////////////////////
    // Sends a register request to the server containing the username and password 
    const handlePress = () => {
        fetch("http://127.0.0.1:5000/auth/register", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify( { username: username, password: password } )
            }
        )
        .then((response) => response.json())

        .then((data) => {
            // If the registration attempt returns an error, store the message in the error variable
            if (data.status === 'error') {
                setError(data.message);
                console.log(error);
                errorMessage.textContent = error;
            }
            // If the registration attempt return a success, route to the login page
            else {
                router.push("/login");
            }
            
        })
        .catch((error) => {
            
        });
        
    }
    ////////////////////////////////////////////////// Send register request //////////////////////////////////////////////////

    // The page that the user sees in the app/browser
    return (

        <View style={styles.container}>
            <StatusBar style="auto" />

            <Text style={styles.title}>Create Account for CU-Bytes</Text>
            <Text style={styles.subtitle}>Create a new CU-Bytes account</Text>

            <Text style={styles.subsubtitle} id="usernameReq">
                Username Requirements:
            </Text>

            <Text style={styles.description} id="usernameUniqueReq">
                - Username is unique to each user
            </Text>
            <Text style={styles.description} id="usernameLengthReq">
                - Between 1 and 80 characters in length
            </Text>
            <Text style={styles.description} id="usernameCharReq">
                - Contains only letters, numbers, and underscores
            </Text>

            <Text style={styles.subsubtitle} id="passwordReq">
                Password Requirements:
            </Text>

            <Text style={styles.description} id="passwordLengthReq">
                - Between 10 and 120 characters in length
            </Text>

            <Text style={styles.description} id="passwordCharReq">
                - At least one lowercase letter, uppercase letter, number and special character 
            </Text>

            <Text style={styles.description} id="errorMessage"></Text>

            {/*Enter the username that will identify the new account*/}
            <TextInput id="usernameInput"
                style={styles.textInput}
                onChange={saveUsernameInputText}
                placeholder={"Enter a new username"}
                value={username}
            >
            </TextInput>

            {/*Enter the password that will secure the new account*/}
            <TextInput id="passwordInput"
                style={styles.textInput}
                onChange={savePasswordInputText}
                placeholder={"Enter a new password"}
                value={password}
                secureTextEntry={true}
            >
            </TextInput>

            {/*Send a request to the server to create a new account with the entered username and password */}
            <TouchableOpacity
                style={[styles.button, loading && styles.buttonDisabled]}
                onPress={handlePress}
                disabled={loading}
            >
                <Text style={styles.buttonText}>
                    Register
                </Text>

            </TouchableOpacity>

        </View>
    )
}